baseURL = "https://criticic.github.io/mlh-gh-pages-site/"
languageCode = "en-us"
title = "Criticic Intro"
theme = "hallo"

publishDir = "docs"

[Author]
    name = "Sagnik Mandal"

[params]
    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/criticic"

    [params.colors]
        background = "#EF476F"
        foreground = "#edf7ff"
        hover = "#ffba82"